export const wordTagsDescription: Record<string, string> = {
  // Miscellaneous sense info
  abbr: "abbreviation",
  aphorism: "aphorism",
  arch: "archaic",
  char: "character",
  chn: "children's language",
  col: "colloquial",
  company: "company name",
  creat: "creature",
  dated: "dated term",
  dei: "deity",
  derog: "derogatory",
  doc: "document",
  euph: "euphemistic",
  ev: "event",
  fam: "familiar language",
  fem: "female term, language, or name",
  fict: "fiction",
  form: "formal or literary term",
  given: "given name or forename, gender not specified",
  group: "group",
  hist: "historical term",
  hon: "honorific or respectful (sonkeigo) language",
  hum: "humble (kenjougo) language",
  id: "idiomatic expression",
  joc: "jocular, humorous term",
  leg: "legend",
  "m-sl": "manga slang",
  male: "male term, language, or name",
  myth: "mythology",
  "net-sl": "Internet slang",
  obj: "object",
  obs: "obsolete term",
  "on-mim": "onomatopoeic or mimetic word",
  organization: "organization name",
  oth: "other",
  person: "full name of a particular person",
  place: "place name",
  poet: "poetical term",
  pol: "polite (teineigo) language",
  product: "product name",
  proverb: "proverb",
  quote: "quotation",
  rare: "rare term",
  relig: "religion",
  sens: "sensitive",
  serv: "service",
  ship: "ship name",
  sl: "slang",
  station: "railway station",
  surname: "family or surname",
  uk: "word usually written using kana alone",
  unclass: "unclassified name",
  vulg: "vulgar expression or word",
  work: "	work of art, literature, music, etc. name",
  X: "rude or X-rated term",
  yoji: "yojijukugo",

  // Part-of-speech info
  "adj-f": "noun or verb acting prenominally",
  "adj-i": "adjective",
  "adj-ix": "adjective - yoi/ii class",
  "adj-kari": "'kari' adjective",
  "adj-ku": "'ku' adjective",
  "adj-na": "adjectival nouns or quasi-adjectives",
  "adj-nari": "archaic/formal form of na-adjective",
  "adj-no": "nouns which may take the genitive case particle 'no'",
  "adj-pn": "pre-noun adjectival",
  "adj-shiku": "'shiku' adjective",
  "adj-t": "'taru' adjective",
  adv: "adverb",
  "adv-to": "adverb taking the 'to' particle",
  aux: "auxiliary",
  "aux-adj": "auxiliary adjective",
  "aux-v": "auxiliary verb",
  conj: "conjunction",
  cop: "copula",
  ctr: "counter",
  exp: "expressions (phrases, clauses, etc.)",
  int: "interjection",
  n: "noun",
  "n-adv": "adverbial noun",
  "n-pr": "proper noun",
  "n-pref": "noun, used as a prefix",
  "n-suf": "noun, used as a suffix",
  "n-t": "noun (temporal)",
  num: "numeric",
  pn: "pronoun",
  pref: "prefix",
  prt: "particle",
  suf: "suffix",
  unc: "unclassified",
  "v-unspec": "verb unspecified",
  v1: "Ichidan verb",
  "v1-s": "Ichidan verb - kureru special class",
  "v2a-s": "Nidan verb with 'u' ending",
  "v2b-k": "Nidan verb (upper class) with 'bu' ending",
  "v2b-s": "Nidan verb (lower class) with 'bu' ending",
  "v2d-k": "Nidan verb (upper class) with 'dzu' ending",
  "v2d-s": "Nidan verb (lower class) with 'dzu' ending",
  "v2g-k": "Nidan verb (upper class) with 'gu' ending",
  "v2g-s": "Nidan verb (lower class) with 'gu' ending",
  "v2h-k": "Nidan verb (upper class) with 'hu/fu' ending",
  "v2h-s": "Nidan verb (lower class) with 'hu/fu' ending",
  "v2k-k": "Nidan verb (upper class) with 'ku' ending",
  "v2k-s": "Nidan verb (lower class) with 'ku' ending",
  "v2m-k": "Nidan verb (upper class) with 'mu' ending",
  "v2m-s": "Nidan verb (lower class) with 'mu' ending",
  "v2n-s": "Nidan verb (lower class) with 'nu' ending",
  "v2r-k": "Nidan verb (upper class) with 'ru' ending",
  "v2r-s": "Nidan verb (lower class) with 'ru' ending",
  "v2s-s": "Nidan verb (lower class) with 'su' ending",
  "v2t-k": "Nidan verb (upper class) with 'tsu' ending",
  "v2t-s": "Nidan verb (lower class) with 'tsu' ending",
  "v2w-s": "Nidan verb (lower class) with 'u' ending and 'we' conjugation",
  "v2y-k": "Nidan verb (upper class) with 'yu' ending",
  "v2y-s": "Nidan verb (lower class) with 'yu' ending",
  "v2z-s": "Nidan verb (lower class) with 'zu' ending",
  v4b: "Yodan verb with 'bu' ending",
  v4g: "Yodan verb with 'gu' ending",
  v4h: "Yodan verb with 'hu/fu' ending",
  v4k: "Yodan verb with 'ku' ending",
  v4m: "Yodan verb with 'mu' ending",
  v4n: "Yodan verb with 'nu' ending",
  v4r: "Yodan verb with 'ru' ending",
  v4s: "Yodan verb with 'su' ending",
  v4t: "Yodan verb with 'tsu' ending",
  v5aru: "Godan verb - -aru special class",
  v5b: "Godan verb with 'bu' ending",
  v5g: "Godan verb with 'gu' ending",
  v5k: "Godan verb with 'ku' ending",
  "v5k-s": "Godan verb - Iku/Yuku special class",
  v5m: "Godan verb with 'mu' ending",
  v5n: "Godan verb with 'nu' ending",
  v5r: "Godan verb with 'ru' ending",
  "v5r-i": "Godan verb with 'ru' ending",
  v5s: "Godan verb with 'su' ending",
  v5t: "Godan verb with 'tsu' ending",
  v5u: "Godan verb with 'u' ending",
  "v5u-s": "Godan verb with 'u' ending",
  v5uru: "Godan verb - Uru old class verb",
  vi: "intransitive verb",
  vk: "Kuru verb - special class",
  vn: "irregular nu verb",
  vr: "irregular ru verb, plain form ends with -ri",
  vs: "noun or participle which takes the aux. verb suru",
  "vs-c": "su verb - precursor to the modern suru",
  "vs-i": "suru verb - included",
  "vs-s": "suru verb - special class",
  vt: "transitive verb",
  vz: "Ichidan verb - zuru verb",

  // Usage domain
  agric: "agriculture",
  anat: "anatomy",
  archeol: "archeology",
  archit: "architecture",
  art: "art, aesthetics",
  astron: "astronomy",
  audvid: "audiovisual",
  aviat: "aviation",
  baseb: "baseball",
  biochem: "biochemistry",
  biol: "biology",
  bot: "botany",
  Buddh: "Buddhism",
  bus: "business",
  cards: "card games",
  chem: "chemistry",
  Christn: "Christianity",
  cloth: "clothing",
  comp: "computing",
  cryst: "crystallography",
  dent: "dentistry",
  ecol: "ecology",
  econ: "economics",
  elec: "electricity, elec. eng.",
  electr: "electronics",
  embryo: "embryology",
  engr: "engineering",
  ent: "entomology",
  film: "film",
  finc: "finance",
  fish: "fishing",
  food: "food, cooking",
  gardn: "gardening, horticulture",
  genet: "genetics",
  geogr: "geography",
  geol: "geology",
  geom: "geometry",
  go: "go (game)",
  golf: "golf",
  gramm: "grammar",
  grmyth: "Greek mythology",
  hanaf: "hanafuda",
  horse: "horse racing",
  kabuki: "kabuki",
  law: "law",
  ling: "linguistics",
  logic: "logic",
  MA: "martial arts",
  mahj: "mahjong",
  manga: "manga",
  math: "mathematics",
  mech: "mechanical engineering",
  med: "medicine",
  met: "meteorology",
  mil: "military",
  mining: "mining",
  music: "music",
  noh: "noh",
  ornith: "ornithology",
  paleo: "paleontology",
  pathol: "pathology",
  pharm: "pharmacology",
  phil: "philosophy",
  photo: "photography",
  physics: "physics",
  physiol: "physiology",
  politics: "politics",
  print: "printing",
  psy: "psychiatry",
  psyanal: "psychoanalysis",
  psych: "psychology",
  rail: "railway",
  rommyth: "Roman mythology",
  Shinto: "Shinto",
  shogi: "shogi",
  ski: "skiing",
  sports: "sports",
  stat: "statistics",
  stockm: "stock market",
  sumo: "sumo",
  telec: "telecommunications",
  tradem: "trademark",
  tv: "television",
  vidg: "video games",
  zool: "zoology",
};

export const miscellaneousInfoTags = [
  "abbr",
  "aphorism",
  "arch",
  "char",
  "chn",
  "col",
  "company",
  "creat",
  "dated",
  "dei",
  "derog",
  "doc",
  "euph",
  "ev",
  "fam",
  "fem",
  "fict",
  "form",
  "given",
  "group",
  "hist",
  "hon",
  "hum",
  "id",
  "joc",
  "leg",
  "m-sl",
  "male",
  "myth",
  "net-sl",
  "obj",
  "obs",
  "on-mim",
  "organization",
  "oth",
  "person",
  "place",
  "poet",
  "pol",
  "product",
  "proverb",
  "quote",
  "rare",
  "relig",
  "sens",
  "serv",
  "ship",
  "sl",
  "station",
  "surname",
  "uk",
  "unclass",
  "vulg",
  "work",
  "X",
  "yoji",
];

export const miscellaneousInfoTagsSet = new Set<string>(miscellaneousInfoTags);

export const partOfSpeechTags = [
  "adj-f",
  "adj-i",
  "adj-ix",
  "adj-kari",
  "adj-ku",
  "adj-na",
  "adj-nari",
  "adj-no",
  "adj-pn",
  "adj-shiku",
  "adj-t",
  "adv",
  "adv-to",
  "aux",
  "aux-adj",
  "aux-v",
  "conj",
  "cop",
  "ctr",
  "exp",
  "int",
  "n",
  "n-adv",
  "n-pr",
  "n-pref",
  "n-suf",
  "n-t",
  "num",
  "pn",
  "pref",
  "prt",
  "suf",
  "unc",
  "v-unspec",
  "v1",
  "v1-s",
  "v2a-s",
  "v2b-k",
  "v2b-s",
  "v2d-k",
  "v2d-s",
  "v2g-k",
  "v2g-s",
  "v2h-k",
  "v2h-s",
  "v2k-k",
  "v2k-s",
  "v2m-k",
  "v2m-s",
  "v2n-s",
  "v2r-k",
  "v2r-s",
  "v2s-s",
  "v2t-k",
  "v2t-s",
  "v2w-s",
  "v2y-k",
  "v2y-s",
  "v2z-s",
  "v4b",
  "v4g",
  "v4h",
  "v4k",
  "v4m",
  "v4n",
  "v4r",
  "v4s",
  "v4t",
  "v5aru",
  "v5b",
  "v5g",
  "v5k",
  "v5k-s",
  "v5m",
  "v5n",
  "v5r",
  "v5r-i",
  "v5s",
  "v5t",
  "v5u",
  "v5u-s",
  "v5uru",
  "vi",
  "vk",
  "vn",
  "vr",
  "vs",
  "vs-c",
  "vs-i",
  "vs-s",
  "vt",
  "vz",
];

export const partOfSpeechTagsSet = new Set<string>(partOfSpeechTags);

export const usageDomainTags = [
  "agric",
  "anat",
  "archeol",
  "archit",
  "art",
  "astron",
  "audvid",
  "aviat",
  "baseb",
  "biochem",
  "biol",
  "bot",
  "Buddh",
  "bus",
  "cards",
  "chem",
  "Christn",
  "cloth",
  "comp",
  "cryst",
  "dent",
  "ecol",
  "econ",
  "elec",
  "electr",
  "embryo",
  "engr",
  "ent",
  "film",
  "finc",
  "fish",
  "food",
  "gardn",
  "genet",
  "geogr",
  "geol",
  "geom",
  "go",
  "golf",
  "gramm",
  "grmyth",
  "hanaf",
  "horse",
  "kabuki",
  "law",
  "ling",
  "logic",
  "MA",
  "mahj",
  "manga",
  "math",
  "mech",
  "med",
  "met",
  "mil",
  "mining",
  "music",
  "noh",
  "ornith",
  "paleo",
  "pathol",
  "pharm",
  "phil",
  "photo",
  "physics",
  "physiol",
  "politics",
  "print",
  "psy",
  "psyanal",
  "psych",
  "rail",
  "rommyth",
  "Shinto",
  "shogi",
  "ski",
  "sports",
  "stat",
  "stockm",
  "sumo",
  "telec",
  "tradem",
  "tv",
  "vidg",
  "zool",
];

export const usageDomainTagsSet = new Set<string>(usageDomainTags);
