export const wordTagToDescription = {
  // Miscellaneous sense info
  abbr: "abbreviation",
  aphorism: "aphorism",
  arch: "archaic",
  char: "character",
  chn: "children's language",
  col: "colloquial",
  company: "company name",
  creat: "creature",
  dated: "dated term",
  dei: "deity",
  derog: "derogatory",
  doc: "document",
  euph: "euphemistic",
  ev: "event",
  fam: "familiar language",
  fem: "female term, language, or name",
  fict: "fiction",
  form: "formal or literary term",
  given: "given name or forename, gender not specified",
  group: "group",
  hist: "historical term",
  hon: "honorific or respectful(sonkeigo) language",
  hum: "humble(kenjougo) language",
  id: "idiomatic expression",
  joc: "jocular, humorous term",
  leg: "legend",
  "m-sl":	"manga slang",
  male: "male term, language, or name",
  myth:	"mythology",	
  "net-sl":	"Internet slang",
  obj:	"object",
  obs:	"obsolete term",
  "on-mim":	"onomatopoeic or mimetic word"	,
  organization:	"organization name"	,
  oth:	"other"	,
  person:	"full name of a particular person"	,
  place:	"place name"	,
  poet:	"poetical term"	,
  pol:	"polite (teineigo) language"	,
  product:	"product name"	,
  proverb:	"proverb"	,
  quote:	"quotation"	,
  rare:	"rare term"	,
  relig:	"religion"	,
  sens:	"sensitive"	,
  serv:	"service",
  ship:	"ship name",
  sl:	"slang"	,
  station:	"railway station"	,
  surname:	"family or surname",
  uk:	"word usually written using kana alone",,
  unclass:	"unclassified name"	,
  vulg:	"vulgar expression or word"	,
  work:"	work of art, literature, music, etc. name"	,
  X:	"rude or X-rated term",
  yoji:	"yojijukugo",
};
